services:
  proj-522:
    image: charlene1010/term-deposit-predictor:4509ab91300d6d7725548bd407dca8958057c4a3
    container_name: proj-522
    ports:
      - "8888:8888"
    volumes:
      - ./:/workplace  # Changed from /home/jovyan/work
    stdin_open: true
    tty: true
