services:
  proj-522:
    image: charlene1010/term-deposit-predictor:cc74da912ea616946f1047311f2d2eee060fd7c5
    container_name: proj-522
    ports:
      - "8888:8888"
    volumes:
      - ./:/workplace  # Changed from /home/jovyan/work
    stdin_open: true
    tty: true
