services:
  proj-522:
    image: charlene1010/term-deposit-predictor:d5c604917cead44284aae291ff8befd6ad7d8aee
    container_name: proj-522
    ports:
      - "8888:8888"
    volumes:
      - ./:/workplace  # Changed from /home/jovyan/work
    stdin_open: true
    tty: true
