name: term-deposit-predictor
channels:
- conda-forge
dependencies:
- altair
- conda-lock=>3.0.4
- jupyterlab
- pandas
- pandera
- pip
- pointblank
- python
- scikit-learn>=1.3.2
- ucimlrepo
- pip:
  - deepchecks
  - vegafusion
  - altair_ally>=0.1.1