name: term-deposit-predictor
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - conda-lock
  - pandas==2.1.4
  - altair
  - ipykernel
  - pip
  - ucimlrepo
  - scikit-learn=1.3.2
  - vegafusion=1.4.3
  - vegafusion-jupyter=1.4.3
  - vegafusion-python-embed=1.4.3
  - vl-convert-python=1.0.1
  - requests=2.31.0
  - notebook=6.5.4
  - jupyter_contrib_nbextensions=0.7.0
  - pip:
    - altair_ally>=0.1.1

