name: term-deposit-predictor
channels:
  - conda-forge
dependencies:
  - python_abi==3.14=8_cp314
  - tzdata==2025b=h78e105d_0
  - bzip2==1.0.8=hd037594_8
  - ca-certificates==2025.11.12=hbd8a1cb_0
  - icu==75.1=hfee45f7_0
  - libcxx==21.1.6=hf598326_0
  - libexpat==2.7.3=haf25636_0
  - libffi==3.5.2=he5f378a_0
  - liblzma==5.8.1=h39f12f2_2
  - libmpdec==4.0.0=h5505292_0
  - libzlib==1.3.1=h8359307_2
  - llvm-openmp==21.1.6=h4a912ad_0
  - ncurses==6.5=h5e97a16_3
  - libgfortran5==15.2.0=h742603c_1
  - libsqlite==3.51.0=h8adb53f_0
  - openssl==3.6.0=h5503f6c_0
  - readline==8.2=h1d1bf99_2
  - tk==8.6.13=h892fb3f_3
  - zstd==1.5.7=h6491c7d_2
  - libgfortran==15.2.0=hfcf01ff_1
  - python==3.14.0=h40d2674_102_cp314
  - libopenblas==0.3.30=openmp_ha158390_3
  - pip==25.3=pyh145f28c_0
  - python-tzdata==2025.2=pyhd8ed1ab_0
  - pytz==2025.2=pyhd8ed1ab_0
  - six==1.17.0=pyhe01879c_1
  - libblas==3.11.0=1_h51639a9_openblas
  - python-dateutil==2.9.0.0post0=pyhe01879c_2
  - libcblas==3.11.0=1_hb0561ab_openblas
  - liblapack==3.11.0=1_hd9741b5_openblas
  - numpy==2.3.5=py314h5b5928d_0
  - pandas==2.3.3=py314ha3d490a_1
prefix: /Users/jacksonlu/miniforge3/envs/term-deposit-predictor
